# Site settings
title: sif6d
email: sif6d@ymail.com
#url:
description: "ASSALAMUALAIKUM WR.WB"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#0033cc'
  links: '#219ab3'

# Footer settings
footer: Sif6d Group

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  #- title: twitter
    #url: https://twitter.com/SBootstrap
  #- title: facebook
    #url:
  #- title: stack-overflow
    #url: http://stackoverflow.com/questions/tagged/jekyll
  #- title: bitbucket
    #url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/sif6d/sif6d.github.io

# Build settings
markdown: kramdown
permalink: pretty
